# Generated by Django 3.1.4 on 2021-09-09 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kontrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50)),
                ('nama_perusahaan', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), website.models.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='isi_kontrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_Purchase', models.CharField(max_length=50)),
                ('nama_barang', models.CharField(max_length=50)),
                ('spesifikasi', models.CharField(max_length=50)),
                ('tujuan', models.CharField(max_length=50)),
                ('satuan', models.CharField(max_length=50)),
                ('jumlah', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('id_kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kontrak')),
            ],
        ),
    ]
