# Generated by Django 3.1.4 on 2021-09-17 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kontrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), website.models.file_size])),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('date_upload', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='perusahaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_perusahaan', models.CharField(max_length=50, unique=True)),
                ('nama_perusahaan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='isi_kontrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kontrak', models.CharField(max_length=50)),
                ('Code_Purchase', models.CharField(max_length=50)),
                ('nama_barang', models.CharField(max_length=50)),
                ('spesifikasi', models.CharField(max_length=50)),
                ('satuan', models.CharField(max_length=50)),
                ('jumlah', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('total', models.IntegerField()),
                ('supplier', models.CharField(default='TOKO AUNIS PRINT OFFSET', max_length=50)),
                ('tgl_order', models.DateField()),
                ('waktu', models.CharField(default='45', max_length=50)),
                ('tgl_penyerahan', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('id_kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kontrak')),
                ('id_perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.perusahaan')),
            ],
        ),
    ]
