# Generated by Django 3.1.4 on 2022-04-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kwitansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kwitansi', models.CharField(max_length=50, unique=True)),
                ('penerima', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='alamat',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='npwp',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='isi_kontrak',
            name='nama_barang',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='isi_kontrak',
            name='spesifikasi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='date_upload',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='kode',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SuratJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(max_length=50)),
                ('pemesan', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('jumlah', models.IntegerField()),
                ('nomor_dos', models.IntegerField()),
                ('id_isikontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.isi_kontrak')),
                ('id_kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kontrak')),
            ],
        ),
        migrations.CreateModel(
            name='SJalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(max_length=50, unique=True)),
                ('pemesan', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('id_kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kontrak')),
            ],
        ),
        migrations.CreateModel(
            name='isi_SJalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('nomor_dos', models.IntegerField()),
                ('id_SJalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sjalan')),
                ('id_isikontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.isi_kontrak')),
            ],
        ),
        migrations.CreateModel(
            name='isi_kwitansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satuan', models.CharField(max_length=50)),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('id_isikontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.isi_kontrak')),
                ('id_kwitansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kwitansi')),
            ],
        ),
    ]
