# Generated by Django 3.1.4 on 2022-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220606_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaan',
            name='nama_perusahaan',
            field=models.CharField(max_length=100),
        ),
    ]
