# Generated by Django 3.1.4 on 2021-09-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210917_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='kwitansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwitansi_type', models.PositiveIntegerField(choices=[(1, 'Siswa'), (2, 'Panitia'), (3, 'admin')], default=1)),
                ('kode_invoice', models.CharField(max_length=50, unique=True)),
                ('nama_perusahaan', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='isi_kwitansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=50)),
                ('spesifikasi', models.CharField(max_length=50)),
                ('satuan', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
                ('jumlah', models.IntegerField()),
                ('total', models.IntegerField()),
                ('id_kwitansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kwitansi')),
            ],
        ),
    ]
