# Generated by Django 3.1.4 on 2022-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220428_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='isi_kwitansi',
            name='harga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isi_kwitansi',
            name='jumlah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isi_kwitansi',
            name='satuan',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
