# Generated by Django 3.0.7 on 2022-01-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_isi_kwitansi_kwitansi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isi_kontrak',
            name='nama_barang',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='isi_kontrak',
            name='spesifikasi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kwitansi',
            name='kwitansi_type',
            field=models.PositiveIntegerField(choices=[(1, 'Kwitansi'), (2, 'Nota')], default=1),
        ),
    ]
