# Generated by Django 3.0.7 on 2022-01-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20220115_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaan',
            name='alamat',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='npwp',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
