# Generated by Django 3.1.4 on 2022-03-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220115_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='SJalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(max_length=50)),
                ('pemesan', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=50)),
                ('jumlah', models.IntegerField()),
                ('nomor_dos', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('id_isikontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.isi_kontrak')),
                ('id_kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kontrak')),
            ],
        ),
    ]
