# Generated by Django 3.1.4 on 2022-03-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_sjalan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sjalan',
            name='id_isikontrak',
        ),
        migrations.RemoveField(
            model_name='sjalan',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='sjalan',
            name='nomor_dos',
        ),
        migrations.CreateModel(
            name='isi_SJalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('nomor_dos', models.IntegerField()),
                ('id_SJalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sjalan')),
                ('id_isikontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.isi_kontrak')),
            ],
        ),
    ]
