# Generated by Django 3.1.4 on 2022-04-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20220412_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kwitansi',
            old_name='nama_perusahaan',
            new_name='penerima',
        ),
        migrations.RemoveField(
            model_name='isi_kwitansi',
            name='total',
        ),
        migrations.RemoveField(
            model_name='kwitansi',
            name='kode_invoice',
        ),
        migrations.RemoveField(
            model_name='kwitansi',
            name='kwitansi_type',
        ),
    ]
