# Generated by Django 3.0.7 on 2022-01-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220111_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='perusahaan',
            name='alamat',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='npwp',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
